export {default as Presentation} from './presentation'
export {default as AboutMe} from './about-me'
export {default as Skill} from './skill'
export {default as Resume} from './resume'
export {default as Contact} from './contact'