export {default as Presentation} from './presentation'
export {default as AboutMe} from './about-me'
export {default as Skill} from './skill'
export {default as Resume} from './resume'
export {default as Contact} from './contact'
export {default as Social} from './social'
export {default as PageTitle} from './page-title'
